version: "2"
services:
    www:
        image: php:7.1.2-apache 
        ports: 
            - "8080:80"
        volumes:
            - ./code:/var/www/html/
        networks:
            - default
    mailhog:
        image: mailhog/mailhog
        ports: 
            - 1025:1025 # smtp server
            - 8025:8025 # web ui
              
volumes:
    persistent: